### ISSUE TITLE
Do not display facets on landing page

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#102]
The facets should not display on the front page of the application. 

![Screen Shot 2021-12-01 at 2.35.10 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/1a39e773-6bf5-4190-9439-e40598d49cd2)

**Comment by jrgriffiniii** [comment]
This was originally proposed in response to the wireframes drafted prior to the development sprint cycles. Currently, there is a preference for this design from the development team (and there has been no negative feedback).
