### ISSUE TITLE
Make sitemap public

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#123]
AFTER the project is available outside of VPN, publish the sitemap so that crawlers start crawling our content.

- [x] Submit the sitemap directly to Google
- [x] Make the sitemap available via robots.txt

See also https://github.com/pulibrary/pdc_discovery/issues/72

**Comment by jrgriffiniii** [comment]
This requires the site to be WWW-accessible (which should hopefully be the case by the end of this two-week cycle).

**Comment by hectorcorrea** [comment]
Sitemap is now public (https://datacommons.princeton.edu/discovery/sitemap.xml), it's listed on robots.txt (https://datacommons.princeton.edu/discovery/robots.txt) and it has been submitted to Google: 

![sitemap_google](https://user-images.githubusercontent.com/568286/160409339-6f850853-a04d-4d5b-9da7-9b7773b42442.png)

Reference: https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap
