### ISSUE TITLE
PRDS logo should be large and prominent

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#148]
**ACCEPTANCE CRITERIA**
- [ ] The PRDS logo in the header should be larger. It should have a height that takes up two UI lines visually, spanning the "Home / About" bar and the search bar.

![Screen Shot 2022-02-07 at 9.37.20 AM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/1e1e250d-5b16-40f1-a065-5445f00731a1)

**Comment by kelynch** [comment]
Include logo and text into design for non-homepage bar.
