### ISSUE TITLE
Reorder Fields on the Show Page

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_discovery#157]
## Preferred order of the fields:
- Title
- Author
- Date (issue date)
- Abstract

This example sets off fields nicely above abstract: [Dryad example](https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.4f4qrfj9t)

## Author field:
Author and issue date should be displayed prominently under the title, as in the [wireframes](https://xd.adobe.com/view/5075f8cb-d37d-44ec-85ec-c2cc43781698-0526/screen/4bf1426a-475d-4510-b495-4655d5365427/).

![Screen Shot 2022-02-15 at 4 11 36 PM](https://user-images.githubusercontent.com/7795797/154150073-ea616ff1-1c0b-4681-badb-ec702ba9c515.png)

## Acceptance Criteria:
- [ ] Fields will show in the order specified: Title, Author, Date, Abstract
- [ ] Author name links are displayed under the title (We do not need to include ORCID ID [the green icon] at this time).
- [ ] Issue date is displayed under author name.

**Comment by hhkitsune** [comment]
@kelynch I'm not sure why this was closed. It doesn't appear to have been completed.

**Comment by hectorcorrea** [comment]
@hhkitsune The rearranged fields are now available in staging (but not yet in production). 

Here are two examples:

* https://pdc-discovery-staging.princeton.edu/catalog/102991
* https://pdc-discovery-staging.princeton.edu/catalog/103832

The second example is hard coded to display the ORCID logo and link for one author (just to show how this could work)

**Comment by hhkitsune** [comment]
I was looking at the production rather than staging version so this is closed.
