### ISSUE TITLE
favicons are not showing

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_discovery#193]
Favicons are not rendering now that we are running under `/discovery`

They currently point to 
```
https://datacommons.princeton.edu/favicon-16x16.png
https://datacommons.princeton.edu/apple-touch-icon.png
```

https://github.com/pulibrary/pdc_discovery/blob/main/app/views/layouts/blacklight/base.html.erb#L15-L18

**Comment by kelynch** [comment]
The favicon should be replaced with the following image - https://drive.google.com/file/d/1MEW3gNVQgWkowE_DVImL_OJHqpbi-QJu/view?usp=sharing
