### ISSUE TITLE
Populate text for "About" page

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#197]
As a Princeton researcher, I want to understand what PDC Discovery is, and how it relates to other data repositories. 

**ACCEPTANCE CRITERIA**
- [ ] The "About" page on the application contains the text in this document: https://docs.google.com/document/d/1MOui-5h1LbC-bqi9DNPv3aH5RffM0OjX2XsEed19hts/edit#

**Comment by hhkitsune** [comment]
@bess I am helping Matt to revise the "About" page early this week to include some new information about the discovery layer. I will let you know when this revision is completed.

**Comment by hhkitsune** [comment]
The [page draft](https://docs.google.com/document/d/1MOui-5h1LbC-bqi9DNPv3aH5RffM0OjX2XsEed19hts/edit#) is now completed.
