### ISSUE TITLE
Display of item with no files

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_discovery#220]
Update the display of the Show page to better display when an item has no files. Below is an example of a record that has no files in DataSpace but the files are in Globus (https://pdc-discovery-staging.princeton.edu/discovery/catalog/88163)

![no-files](https://user-images.githubusercontent.com/568286/157888088-a6fda4d2-384a-4bb6-941f-2527c5091f29.png)

I noticed this once we started importing only "visible" files from DataSpace (https://github.com/pulibrary/pdc_discovery/issues/218)

**Comment by bess** [comment]
Here is a very simple removal of the files table when there are no files in DataSpace. I cannot actually find an object in production where this is the case, however. 

<img width="825" alt="Screen Shot 2022-03-15 at 4 51 51 PM" src="https://user-images.githubusercontent.com/65608/158470477-32e1e22b-9524-412a-8346-0734bec59264.png">
