### ISSUE TITLE
Align font and layout design with University guidelines for design accessibility

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/pdc_discovery#221]
[Princeton OIT has standard guidelines for legibility](https://accessibility.princeton.edu/how/design#legibility), among other things. For the main content on an item page, the metadata fields should have the following characteristics:

- [ ] Ample space separating grouped elements
- [ ] Sans-serif font
- [ ] Line heights (leading) close to 1.5
- [ ] Line lengths less than 80 characters
- [ ] Left-side justification
- [ ] Medium or heavy-weight font face
- [ ] High color contrast (black text on white background is best)

[Princeton OIT also has recommendations for testing for accessibility](https://accessibility.princeton.edu/how/test), including a consultation with on-campus experts (who seem eager to help).

**Comment by hhkitsune** [comment]
@matthewjchandler and All, let's hold off from this feature for the moment. We will be discussing this issue in our meeting today. Thanks!

**Comment by hhkitsune** [comment]
Closing for now, we may return to this ticket in the future.
