### ISSUE TITLE
Whitespace after banners on iphone XR

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_discovery#262]
## Due Date

**Proposed date:** flexible, 4/22

**Reason:** Issue is not on fire. Please consider completion within a reasonable timeframe.

## Description 

See images below for appearance on iPhone XR.

The upper and lower banners aren't meeting the right side of the screen, which creates a small whitespace. Notice how the lettering from the logo extends past the banner in the top image.

## Acceptance Criteria

- [ ] Determine if the issue is persistent across phone devices or just certain models 
- [ ] Determine if the problem may be fixed
- [ ] The banners will (ideally) display across most screens without an awkward whitespace

## Image (top):

![iphone_xr_discovery2](https://user-images.githubusercontent.com/50670293/162778986-0a82be3b-4d7f-49f8-9287-4762ef64c914.jpg)

## Image (bottom; note the black line is a normal feature on the iPhone and not an error):

![iphone_xr_discovery1](https://user-images.githubusercontent.com/50670293/162779049-4ed6dd66-bdb9-4804-a563-b38ac14cf396.jpg)

**Comment by matthewjchandler** [comment]
I see a similarly awkward presentation of the top of the home page on Chrome on Android, and I might guess that formatting around the PDC Discover logo is an issue:

![Screenshot_20220411-124355](https://user-images.githubusercontent.com/66128387/162789962-e80d1054-804b-4a49-911a-454ad1b7b3c3.png)
