### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#267]
The main branch of pdc_discovery currently won't run locally for @bess and @kelynch because of this error: 

![Screen Shot 2022-05-03 at 11 22 26 AM](https://user-images.githubusercontent.com/65608/166483808-b02c2c5f-aa52-40c3-9dc2-23bc152477a1.png)

ACCEPTANCE CRITERIA
- [ ] Write a regression test that re-creates this error
- [ ] Fix it
- [ ] Report back to the team what caused it

**Comment by hectorcorrea** [comment]
This looks promising: https://github.com/rails/rails/issues/42261

**Comment by hectorcorrea** [comment]
The issue seems to be with gem `xray-rails` which we only use in development (do we even use it?). If we remove that gem from the Gemfile it works with no problems.
