### ISSUE TITLE
Track citation copy/download behaviors

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_discovery#299]
Using Plausible custom events, start tracking when users click the "copy" button for text-formatted citations, and the "copy" or "download" buttons for BibTex-formatted citations.

Text-formatted citation "copy" button: 
<img width="775" alt="Screen Shot 2022-05-25 at 3 15 13 PM" src="https://user-images.githubusercontent.com/7795797/170351014-c163e1ff-bb66-48b7-ac75-a7871ef7fdd2.png">

BibTex-formatted citation "copy" and "download" buttons:
<img width="775" alt="Screen Shot 2022-05-25 at 3 15 25 PM" src="https://user-images.githubusercontent.com/7795797/170351171-7442ff4f-150d-4dae-baef-c74a0b8f90cb.png">

There are already events in the system for the contents download.  This will be similar to that event, but will be a different plausible [function](https://github.com/pulibrary/pdc_discovery/blob/eab47ef78b7c0eb6467ae1558b4472aa6228c714/app/assets/javascripts/plausible.js#L4).

This will be complete when:

- [ ] When the text copy button is clicked on the page an event is sent to plausible
- [ ] When the BibTeX copy button is clicked on the page an event is sent to plausible
- [ ] When the BibTeX download button is clicked on the page an event is sent to plausible
- [ ] We have an automated test to make sure this continues.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/299?planning-poker) with Zenhub @hectorcorrea @jrgriffiniii @bess
