### ISSUE TITLE
Feature: Turn off/on Measures Display for individual records

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_discovery#301]
## Description

Administrative users (i.e., Matt, Neggin, Wind, Hannah and other curators or administrators as may be identified) would like the ability to turn off the measures display for individual records (page views and downloads) so that it does not display publicly on a specific selected record's page. We do want administrators to be able to obtain this information on the back end, even if the display feature is set to *off*. We would like to be able to turn the feature on again if needed. 

### Scenario 1

Anaïs was alarmed to see that her deposit's measures (page views and downloads) were so low. She had been working on a particularly tedious grant application that cited the project associated with her data deposit. The low numbers made her fearful that grantprovider.gov wouldn't consider her application. She thought to herself, "How could these numbers be so low when I know my project had impact within the field of Medieval French Literature Studies?" Anaïs had hovered over the measures feature (see: [Discovery #300](https://github.com/pulibrary/pdc_discovery/issues/300)) but was just too frustrated to read most of the message. She did contact the email provided for help, and Neggin the curator responded. After patiently listening to Anaïs's tale, Neggin explained that per her request, administrators are able to disable the visibility of the measures, though the feature information is still available to admin-users on the back end. Neggin let Anaïs know that she may request to have the visibility re-enabled in the future if she changes her mind. Anaïs felt relieved and was pleased with Neggin's assistance.

### Scenario 2

Neggin the curator was casually viewing a recently published astronomy dataset when she noticed something looked very wrong with the numbers in the measure feature. The numbers for downloads were exceptionally high, but the page views were only two. This just didn't add up. She checked a few other records, but the problem seemed isolated to the astronomy dataset. Fortunately, Neggin was able to use the "turn off measures display" feature so that users wouldn't get the wrong idea about this record. She then requested the assistance of our development team to address the underlying issue. Neggin will be able to turn the feature back on when it is working properly.

## Acceptance Criteria

- [ ] Admin users will be able to turn off (or on) the display of the measures (page views, downloads) for any individual record
- [ ] Turning off the display will have no affect on the data being gathered, so this information can still be accessed by administrative users on the back end.
- [ ] Admin users can easily switch off/on using a button, switch, checkbox or some other easy means of accessing these commands.

**Comment by carolyncole** [comment]
Added a large estimate, because PDCDiscovery does not have the concept of logging in, and/or administrators at this point.  Those tickets would need to be created and completed before this can really be actionable.
