### ISSUE TITLE
Build a second production server

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#311]
We recently had a production outage because the disk behind pdc discovery production went down.

- [x] Build a second instance of pdc discovery production
- [x] It should be load balanced with the existing instance
- [x] When we deploy code to prod it should go to both systems

**Comment by jrgriffiniii** [comment]
Following the merging of https://github.com/pulibrary/princeton_ansible/pull/3166/files, https://github.com/pulibrary/pdc_discovery/blob/main/config/deploy/staging.rb and https://github.com/pulibrary/pdc_discovery/blob/main/config/deploy/production.rb will need to be updated.
