### ISSUE TITLE
Disk usage

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_discovery#312]
[This spreadsheet](https://docs.google.com/spreadsheets/d/1Kl8JVEjE7tDSzgYWPoDl6PZHyNMq6hNLuH-GKwH602w/edit#gid=1201843391) reports that PDC Discovery is using 37GB of disk space (out of 40GB allocated). 

Where are the 37GB coming from?

This is what `du` returns on the box:

```
deploy@pdc-discovery-prod1:~$ du -h -s /opt/pdc_discovery/shared/log/
769M	/opt/pdc_discovery/shared/log/

deploy@pdc-discovery-prod1:~$ du -h -s /opt/pdc_discovery
2.3G	/opt/pdc_discovery

deploy@pdc-discovery-prod1:~$ du -h -s /
9.7G	/
    (but it skipped many folders due to permissions)
```

**Comment by jrgriffiniii** [comment]
I can confirm that I am having difficulties with finding these exact metrics as well. Further, the logrotate configuration seems to be valid:

```bash
pulsys@pdc-discovery-prod1:/var/log$ cat /etc/logrotate.d/pdc_discovery
# Default logrotate configuration for a Rails App in Ansible managed

/opt/pdc_discovery/current/log/*.log {
  minsize 500M
  daily
  rotate 5
  copytruncate
  delaycompress
  compress
  notifempty
  missingok
  su root root
}
```

**Comment by acozine** [comment]
I saw the same parameters as everyone else. I do not think the VM is at risk of running out of disk space - it has plenty of available space.

The spreadsheet was generated out of vSphere, and according to John, the values for disk usage in vSphere/VMware relate to the space the entire VM occupies on the host. Even though the 40GB disk is thin-provisioned, the VM is currently "taking up" 37 of those 40GB.
