### ISSUE TITLE
Display abstract and description

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#32]
**ACCEPTANCE CRITERIA**
- [ ] Display abstract and description
- [ ] Abstract and description fields both have a "show less / show more" toggle

![Screen Shot 2021-08-09 at 3.51.24 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/6e94e0f2-2bf5-4b03-8251-696ff1750bba)

Reference: https://xd.adobe.com/view/dcea8b14-7f9f-4bf2-bc97-368c2f31e75b-89b9/screen/4bf1426a-475d-4510-b495-4655d5365427

**Comment by kelynch** [comment]
Show less/show more is currently used in the catalog and in DPUL.  Can we base this work off of that?
