### ISSUE TITLE
Allow the DOI and ark as part of the URL(s) 

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_discovery#328]
Instead of just the object id allow an object to be found by the DOI also.

In addition we will need to allow the ARK to be part of the URL if one exists.

See orangelight for an example: https://github.com/pulibrary/orangelight/blob/main/config/routes.rb#L70-L73

This is complete when:

- [x] An item can be found by  the doi  `/doi/:id`
- [x] An item can be found by the ark `/ark/:id`
- [x] There are automated test that prove the above look ups work

**Comment by carolyncole** [comment]
@kelynch I saw that you change the title to the ticket.  Are you assuming that the URL would contain BOTH an ark and a DOI?  I was assuming that it would contain either an ARK OR a DOI, but not both.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/pdc_discovery/commit/149ef80ff8d648bd7ea3985f20e4b4cef671bbdc resolves this for `pdc_discovery` (I apologize, I just need to clean this and ensure proper test coverage before opening a PR).
