### ISSUE TITLE
Fix color-adjust deprecation

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#330]
Running the tests currently raises this deprecation warning:
```
autoprefixer: /Users/bess/projects/pdc_discovery/app/assets/stylesheets/application.scss:4181:3: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
autoprefixer: /Users/bess/projects/pdc_discovery/app/assets/stylesheets/blacklight.scss:4181:3: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated
```

ACCEPTANCE CRITERIA
- [ ] Fix the problem
- [ ] Run the tests to ensure it has been fixed

**Comment by leefaisonr** [comment]
The problem is not in our local application, it is located upstream (most likely in Blacklight). This will be fixed when we update Blacklight.
