### ISSUE TITLE
First pass at PDC Describe indexing in PDC Discovery

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#340]
## ACCEPTANCE CRITERIA
- [x] PDC Describe content is indexed into PDC Discovery enough that page display looks mostly right.
- [x] If there are places where this is challenging, make a separate ticket for discussion with the team
- [x] ~~PDC Discovery is indexing content from both PDC Describe and DataSpace. These records are de-duplicated, and preference is given to PDC Describe works. De-duplication can be based on DOI or ARK.~~ (moved to https://github.com/pulibrary/pdc_discovery/issues/375)

**Comment by bess** [comment]
Current state of a solr record for our first sample: 
```
     {
        "id":"doi-10-34770-r75s-9j74",
        "author_tesim":["Trueman, Daniel",
          "Wang, Matthew",
          "Villalta, Andrés",
          "Chou, Katie",
          "Ayres, Christien"],
        "title_tesim":["bitKlavier Grand Sample Library—Binaural Mic Image"],
        "publisher_ssim":["Princeton University"],
        "hashed_id_ssi":"c1b9e120d1b6416d",
        "timestamp":"2022-10-06T15:43:33.337Z",
        "score":2.682568}]
  },
```

**Comment by kelynch** [comment]
Work toward this feature has been done on https://github.com/pulibrary/pdc_discovery/pull/345 and will be merged.  The feature is not yet complete once this has been merged, but we will pause on completing it until the sample records from DataSpace are mapped completely into DataCite and confirmed as accepted by RDOS.
