### ISSUE TITLE
Downloadable report for OSTI reporting

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_discovery#355]
PPPL needs to provide a list of their datasets to OSTI on a regular basis. (E-Link 241.6 submissions)

PDC Discovery should provide an easy way to download a set of search results as a json formatted report.  We propose a PPPL-specific dedicated JSON endpoint in the discovery application (similar to [this](https://datacommons.princeton.edu/discovery/?f[community_root_name_ssi][]=Princeton+Plasma+Physics+Laboratory&q=&search_field=all_fields&fl=*&format=json)). 

### Acceptance criteria
- [x] There should be an API endpoint so Chun can easily incorporate the download into PPPL workflows
    * Chun: I think this has been accomplished via https://github.com/pulibrary/pdc-osti/commit/368dee35a95c735040034cfc0d7b9f210ed6e6a3
- [x] Each record in the report should contain the following fields:
  - [x] Title
  - [x] Funding information
  - [x] ARK handle
  - [x] DOI
  - [x] Abstract
  - [x] Description (will merge this with the Abstract)
  - [x] Author list, nested per author so that ORCID may also be included (right now the list is semicolon separate but does not contain additional information, such as ORCID)
  - [x] Issue date in ISO format (YYYY-MM or YYYY)
  - [x] isReferencedBy (for related journal articles)
- [x] It needs pagination so Chun can get all of the records

**Comment by carolyncole** [comment]
@astrochun just a clarification utilizing an example: https://datacommons.princeton.edu/discovery/catalog/133856

* Title: Correlation between the relative blob fraction and plasma parameters in NSTX
* Funding Information: U. S. Department of Energy contract number DE-AC02-09CH11466
* ARK handle: http://arks.princeton.edu/ark:/88435/dsp01qb98mj62b
* DOI:  https://doi.org/10.1063/5.0074261
* Description: data of figures used in this publication
* Author List: Zweben, S,J., Banerjee, S, Bisai, N, Diallo, A, Lampert, M, LeBlanc, B, Myra, JR, & Russell, D.A. (No ORCID is currently present)
* Issue Date: 18 January 2022
* is referenced by: https://doi.org/10.1063/5.0074261

**Comment by carolyncole** [comment]
@astrochun What time schedule are you looking for this?  After dataspace is fully migrated and turned off, or before?

**Comment by astrochun** [comment]
> @astrochun What time schedule are you looking for this? After dataspace is fully migrated and turned off, or before?

Would like this to happen before it's turned off. This will ensure that we have two ways to retrieve the complete metadata.

**Comment by carolyncole** [comment]
@astrochun Do you have an example of a report you have already gotten from Dspace?  It would be helpful to see what you are getting.

**Comment by astrochun** [comment]
> @astrochun Do you have an example of a report you have already gotten from Dspace? It would be helpful to see what you are getting.

This is what [`dspace-osti`](https://github.com/pulibrary/dspace-osti) dumps from the DataSpace JSON API: https://raw.githubusercontent.com/pulibrary/dspace-osti/main/data/dspace_scrape.json

**Comment by kelynch** [comment]
The above payload is pulled currently from the DataSpace API endpoint defined [here](https://github.com/pulibrary/dspace-osti/blob/2b074352da4943711e2c16faa1a7243d36d1e730/Scraper.py#L125).  

The collection IDs used to populate that string are defined in [this array](https://github.com/pulibrary/dspace-osti/blob/2b074352da4943711e2c16faa1a7243d36d1e730/Scraper.py#L16-L30).

**Comment by bess** [comment]
Per discussion with @astrochun, he now has what he needs to evaluate what the reporting process might look like. He's going to play around with what's been implemented already and think about whether this is the right direction, or whether we should instead try to generate a feed of the datacite JSON (as opposed to the indexed PDC Discovery data, which is what we've used so far).
