### ISSUE TITLE
URI and ReferencedBy ark and DOI values should appear in citations

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_discovery#357]
The ark IDs and (if present) DOI values that appear in the ReferencedBy field for objects should be included in the citation field on the show page.

Example (item has both an ark and a ReferencedBy DOI and neither appears in the citation): 
https://datacommons.princeton.edu/discovery/catalog/137079

Note that DOIs in the URI field are appearing appropriately in the citation, example: https://datacommons.princeton.edu/discovery/catalog/125444

**Comment by carolyncole** [comment]
![Screenshot 2023-08-02 at 11.42.54 AM.png](https://images.zenhubusercontent.com/5c925e2d9d1bd30b8d310436/b3831798-511c-40a1-8db5-703a61c65735)

**Comment by carolyncole** [comment]
Should we really be putting referenced by DOIs into the citation?  It seems like only the DOI of the object should be in the citation.  We do believe the Ark should be put in the citation.  Comment from meeting with @bess @hectorcorrea and @jrgriffiniii

**Comment by carolyncole** [comment]
We clarified that this should not be done.
