### ISSUE TITLE
Author ordering for PDC Describe records

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_discovery#376]
In **PDC Describe** we allow users to sort authors in a specific order. We currently don't import that information into **PDC Discovery** and therefore we cannot enforce the original order once the record has been imported. 

If we want to we could import this data and preserve the original author order when displaying the records in PDC Discovery.

Part of #340 

- [x] verify that pdc describe exports the explicit author order
- [x] Change the indexing to store a json snippet
- [x] Change the display to reflect the order in the json snippet
- [x] Automated test to see the order is applied to Authors in the UI

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/376?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii @kelynch
