### ISSUE TITLE
Add a statement to the README

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_discovery#385]
We would like to indicate that this is not off the shelf software and that it was custom created for Princeton.  Although the source is open it is not intended to be picked up and utilized by another organization.

I am not sure what the exact wording on the page should be, so for the moment this is a place holder ticket to make sure we do not forget.

**Comment by hhkitsune** [comment]
It might be useful to point out something like: 

This software was created and customized to address the unique needs for a research data repository that are localized to Princeton University. It would not be usefully applied as-is for another institution. However, the code is open-sourced and we hope others will find our ideas inspirational, and that aspects of our code may be useful, when addressing their unique needs for infrastructure.
