### ISSUE TITLE
Search by ORCID

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#392]
I should be able to put an ORCID into the search box and return all records that have an author or contributor with that orcid ID.

This is requested by Chun and the ORCID working group.

Acceptance criteria:

- [ ] Add ORCID to the Indexer
- [ ] When ORCID is pasted into All-Fields  it should be found
- [ ] Automated tests to see if an ORCID is indexed
- [ ] Automated tests to see if an ORCID can be found

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/392?planning-poker) with Zenhub @bess @jrgriffiniii
