### ISSUE TITLE
Integrate a11y audits into the CircleCI builds

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pdc_discovery#41]
Goal: Establish automated accessibility checking early in the development process, so we ensure that the UI we build works for a wide range of people and web crawlers. 

**ACCEPTANCE CRITERIA**
- [ ] Our CI process automatically checks accessibility, via `axe-core-rspec`

**Comment by jrgriffiniii** [comment]
https://circleci.com/developer/orbs/orb/foo-software/lighthouse-check provides an example Orb that may serve as inspiration for a solution to this.

**Comment by christinach** [comment]
> This advances #39 using https://developers.google.com/web/tools/lighthouse
> 
> @christinach If, given your recent work on accessibility, you recommend a different approach, please say so.

Including lighthouse in cicleci yes it would be one approach. Also another way is to use the gem 'axe-core-rspec'https://github.com/pulibrary/orangelight/commit/94f962736db2d2dd6b06a4dbb656d77648ca38e7#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR103
