### ISSUE TITLE
OSTI reporting feed is blank

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#420]
@astrochun is reporting that the PPPL / OSTI reporting feed has gone blank unexpectedly.

![Screenshot 2023-04-18 at 1.52.55 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/e229a3ab-679a-46f7-a189-200f311ec4c7)

**Comment by bess** [comment]
The issue was that after the recent reindex the DataSpace records were showing up in the search first. Since they don't have the `pdc_describe_json_ss` field, the feed appeared to be blank. I've adjusted the query behind this feed to only include records from PDC Describe.

**Comment by astrochun** [comment]
> The issue was that after the recent reindex the DataSpace records were showing up in the search first. Since they don't have the `pdc_describe_json_ss` field, the feed appeared to be blank. I've adjusted the query behind this feed to only include records from PDC Describe.

So is this fixed on stage or prod? Let me know when you think I can retest.
