### ISSUE TITLE
Redirect collection ARKs from DataSpace to PDC Discovery

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_discovery#426]
This should be done as a final task per collection in the data migration.

We should likely update URL redirects using the [EZID client gem](https://github.com/duke-libraries/ezid-client).

## Examples
- [ ] Example: [Digital Humanities Community](https://arks.princeton.edu/ark:/88435/dsp018p58pg869) and [Digital Humanities - Research Data Sets](https://arks.princeton.edu/ark:/88435/dsp014x51hm942), while two different ARKs, should both redirect to [Digital Humanities facet](https://datacommons.princeton.edu/discovery/?f%5Bcommunity_root_name_ssi%5D%5B%5D=Digital+Humanities) in PDC Discovery.
- [ ] [Princeton Plasma Physics Laboratory](https://arks.princeton.edu/ark:/88435/dsp01pz50gz45g) in DataSpace should redirect to [Princeton Plasma Physics Laboratory](https://datacommons.princeton.edu/discovery/?f%5Bcommunity_root_name_ssi%5D%5B%5D=Princeton+Plasma+Physics+Laboratory) in PDC Discovery.
- [ ] [Princeton Plasma Physics Laboratory > Spherical Torus > NSTX-U in DataSpace](https://arks.princeton.edu/ark:/88435/dsp011v53k0334) should redirect to [NSTX-U](https://datacommons.princeton.edu/discovery/?f%5Bcollection_name_ssi%5D%5B%5D=NSTX-U&f%5Bcommunity_root_name_ssi%5D%5B%5D=Princeton+Plasma+Physics+Laboratory&f%5Bsubcommunity_name_ssi%5D%5B%5D=Spherical+Torus) in PDC Discovery.
- [ ] 

## Acceptance Criteria

- [x] Create a Rake task that can be run on a per collection basis
        Note-  the dspace ark for the collection is part of the url ark:/88435/dsp011v53k0334 https://arks.princeton.edu/ark:/88435/dsp011v53k0334, which becomes https://dataspace.princeton.edu/handle/88435/dsp011v53k0334 now, which should become https://datacommons.princeton.edu/discovery/?f%5Bcollection_name_ssi%5D%5B%5D=NSTX-U&f%5Bcommunity_root_name_ssi%5D%5B%5D=Princeton+Plasma+Physics+Laboratory&f%5Bsubcommunity_name_ssi%5D%5B%5D=Spherical+Torus
   This is done by a human not the code
- [x] The [docmentation for migration](https://github.com/pulibrary/pdc_describe/blob/main/architecture-decisions/0008-migration-from-dataspace.md) is updated with instructions for running the rake task

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/426?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii
