### ISSUE TITLE
Search box in header

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#43]
![Screen Shot 2021-08-09 at 4.17.40 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/7c24159c-c7ea-4e45-a336-64084eb771f6)

- [ ] Implement a search box in the header, for all pages *except* the front page

**Comment by jrgriffiniii** [comment]
This has been discussed with stakeholders, and it may not be desirable compared to what is currently offered in the design.
