### ISSUE TITLE
Record is Missing Globus Button

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_discovery#450]
## Description

PRDS reported a Globus button missing from the following record in PDC Discovery: https://datacommons.princeton.edu/discovery/catalog/172591.

## Image shows the Globus link in the description, but the Globus button is missing from the download section

![Screen Shot 2023-07-11 at 4 36 54 PM](https://github.com/pulibrary/pdc_discovery/assets/50670293/a599f2e2-a261-4c28-bcc3-a76cb844136c)

## Acceptance Criteria
- [x] Globus button will appear as expected for this record

**Comment by hectorcorrea** [comment]
The issue here is that this record does not have a Globus URI in the URI metadata fields coming from DataSpace. The referenced PR will update the code to also look in the description for the Globus URI.
