### ISSUE TITLE
Error connecting to Plausible

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_discovery#462]
HoneyBadger has recorded a few instances in which we cannot connect to Plausible to get download statistics (https://app.honeybadger.io/projects/95072/faults/85367388) and pageview statistics (https://app.honeybadger.io/projects/95072/faults/85327267). 

It is not too often or too worrisome, but perhaps we should investigate.

**Comment by carolyncole** [comment]
perhaps add a retry, but we will wait to see if we see this more often before changing the code

**Comment by hectorcorrea** [comment]
This issue happened again, it looks like heavy traffic to https://datacommons.princeton.edu/discovery/catalog/108913 (Shakespeare and Company Project Dataset: Lending Library Events)

What's strange is that this page is not even listed in the top 20 in Plausible:

![Screenshot 2023-12-01 at 4 04 25 PM](https://github.com/pulibrary/pdc_discovery/assets/568286/b1efa75f-ad76-4295-a46d-4c65832d36d1)
