### ISSUE TITLE
Once an author modal is opened, there is no way to close it

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#469]
In Firefox, and PDC Discovery v1.14.0, when you open a modal for more information about an author there is no way to close it.

![Screenshot 2023-08-08 at 3 55 42 PM](https://github.com/pulibrary/pdc_discovery/assets/65608/014876bc-a2eb-41cd-8528-d22619e2102a)

**Comment by hectorcorrea** [comment]
You can close it by clicking the link again, which evidently it is not very obvious. We'll see if we can add a "close" button to the pop up.
