### ISSUE TITLE
Newly approved works from Describe are not appearing in the index on Discovery

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#482]
I've observed this for the past couple of days, and I've tried a few things to make sure I'm really seeing what I think I'm seeing. Newly approved works from PDC Describe are not appearing in PDC Discovery, even after a reindex. Except then, sometimes a day later, they appear! 

How to tell: There are currently 17 items in the rss feed from pdc describe (See https://pdc-describe-prod.princeton.edu/describe/works.rss) but only 15 items from PDC Describe in Discovery, even after a reindex.

**Comment by hectorcorrea** [comment]
I reindexed locally using production as the source data from DataSpace and PDC Describe and got all 17 PDC Describe records. I tried several combinations (clear the Solr and reindex, don't clear Solr and reindex) and in every case I got all 17 PDC Describe records.

I re-ran the reindex in production and all 17 records came through!

```
$ cd /opt/pdc_discovery/current
$ bundle exec rake index:research_data
```

 ¯\_(ツ)_/¯

**Comment by bess** [comment]
@hectorcorrea I don't know why this would be the case, but indeed when I run `rake index:research_data` I get all of the PDC Describe records, but when I only run `rake index:pdc_describe_research_data` I don't.

I'm going to update the reindex accordingly so we'll see new PDC records faster.

**Comment by hectorcorrea** [comment]
@bess we might be running into the same problem we had before in which one of the replicas was getting the data but not the other. The fast reindex `rake index:pdc_describe_research_data' does not blow away the Solr collection but the slow one `rake index:research_data` does. 

So maybe my "great" idea of using the fast one on the every 30 minutes cronjob is not that great after all 🙃
