### ISSUE TITLE
Add the More option to the sub-communities facet

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#496]
This work: https://pdc-describe-prod.princeton.edu/describe/works/62
is a PPPL work with two subcommunities, `Advanced Projects` and `System Studies`. I would therefore expect that I could find it by selecting PPPL from communities, and "System Studies" from subcommunities. However, System Studies isn't there. 

However, by typing it manually into the URL, I can find the expected work: https://datacommons.princeton.edu/discovery/?f[communities_ssim][]=Princeton+Plasma+Physics+Laboratory&f[subcommunities_ssim][]=System+Studies

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnlXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--34cdcf98869f7ed883f89cbd5a040d25dfafd3f9/Screenshot%202023-09-13%20at%2011.20.38%20AM.png)

## Acceptance Criteria
- [ ] There is a "more" option at the bottom of the facets so we can see all of the values, not just the most populated ones
- [ ]  If it is easy add in the more to all facets except the date selector (it is a blacklight configuration option)

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/496?planning-poker) with Zenhub @bess @jrgriffiniii @kelynch

**Comment by carolyncole** [comment]
closed by https://github.com/pulibrary/pdc_discovery/pull/505
