### ISSUE TITLE
Error in search result links

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_discovery#498]
Steps to reproduce

1. Go to the home page: https://datacommons.princeton.edu/discovery/ 

The page loads fine, but if you open the console in your browser and you'll notice a Cross-Origin warning because something is pointing to `pdc-discovery-prod.princeton.edu`

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 
https://pdc-discovery-prod.princeton.edu/discovery/catalog/range_limit?range_end=2023&range_field=year_available_itsi&range_start=2013. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
Status code: 200.
```

2. Filter by any facet, e.g. https://datacommons.princeton.edu/discovery/?f%5Bdomain_ssim%5D%5B%5D=Natural+Sciences

3. Now click on any of the search result links (e.g. https://datacommons.princeton.edu/discovery/catalog/165364/track?counter=1&document_id=165364&search_id=975648)

and you'll get the error page "Looks like something went wrong!"

notice how the search result link has an extra `/track?counter=...` at the end. 

I suspect the culprit is the cross-origin error. That is what is causing Blacklight to generate the bogus URLs with the `/track?counter=...` at the end

**Comment by hectorcorrea** [comment]
A few more information
* @carolyncole noticed that the error only happens if you start on https://datacommons.princeton.edu/discovery/, everything works fine if you start from https://pdc-discovery-prod.princeton.edu/discovery/ 
* Should we consider having just one valid URL (e.g. https://datacommons.princeton.edu/discovery) and redirect https://pdc-discovery-prod.princeton.edu/discovery/  to it (?)
* These issues are being reported in HoneyBadger as `ActionView::MissingTemplate` https://app.honeybadger.io/projects/95072/faults/84621197

**Comment by bess** [comment]
I found this command: 
```
curl -s -D - -H "Origin: https://pdc-discovery-prod.princeton.edu/" https://datacommons.princeton.edu/discovery/ -o /dev/null
```

This lets us test whether content from `https://pdc-discovery-prod.princeton.edu` is permitted to load on page `https://datacommons.princeton.edu/discovery`. It isn't. We knew that already, but this is a useful debugging tool. 

Here is the output: 
```
HTTP/2 200
server: nginx/1.25.1
date: Tue, 05 Sep 2023 20:42:26 GMT
content-type: text/html; charset=utf-8
status: 200 OK
cache-control: max-age=0, private, must-revalidate
vary: Accept, Origin
referrer-policy: strict-origin-when-cross-origin
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
x-request-id: 4afca45a-2962-43fa-9b25-e765ef6a9f2f
link: </discovery/assets/application-40c09398f416956605a9cfca139e988a24eb89cd4775374ab945de1f5903a113.css>; rel=preload; as=style; nopush,</discovery/assets/application-6a7ba76bf4d9388805be0e2e1810d38ea497d29ea39ac568cb69b1b4c2889e45.js>; rel=preload; as=script; nopush
x-download-options: noopen
etag: W/"9ddf7c40944edbb571bc92732b9002ab"
x-frame-options: SAMEORIGIN
x-runtime: 0.185426
x-content-type-options: nosniff
set-cookie: _pdc_discovery_session=E9SjkO5yY8O8pjm14pw1ob%2FJXrVMknZwxW8QAgRxwSkMiSIroox%2B7IAp9fYrXoh1kxG3uYmXawD7sSF0VAZFznGbGSAScqnwJhtVw5Wae2ZhcXWrLSZ8qQWCBmauTIBYWKjJCkawA4iHaeTU3znPSxF%2BvfLTvFqRb2pBRrQ%2Bpr%2B19n4S7LrWUo9WB8nEzUos9FHrUxzJWbgFl37TYsSPSLWCOGMOTPyFRxioi5UB15lpxBtJee6RN6kQQSZlYSXJ%2FrYcvjImOR0Ne3c5s%2FwKgrdU%2FPIxCtFKlG3R%2FhAY--%2B6fKot%2BjTamMG7Ve--kx2CaM4%2F580tgQDWxEu%2BEA%3D%3D; path=/; HttpOnly; SameSite=Lax
x-powered-by: Phusion Passenger(R) 6.0.18
```
