### ISSUE TITLE
Solr indexing broken in staging

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#510]
Most relevant bit seems to be: `Error adding field 'embargo_date_dtsi'='[]'`

 [pdc_discovery/staging] Notice: Error importing record from https://pdc-describe-staging.princeton.edu/describe/works/472.json. Exception: Traject::SolrJsonWriter: Exceeded maximum number of skipped records (0): aborting: Unexpected HTTP response status 400 from POST http://lib-solr8-staging.princeton.edu:8983/solr/pdc-discovery-staging-2/update/json: ERROR: [doc=doi-10-80021-aj79-nf88] Error adding field 'embargo_date_dtsi'='[]' msg=Invalid Date String:'' #510 

## Backtrace

    line 91 of [PROJECT_ROOT]/app/lib/describe_indexer.rb: rescue in block in perform_indexing
    line 86 of [PROJECT_ROOT]/app/lib/describe_indexer.rb: block in perform_indexing
    line 85 of [PROJECT_ROOT]/app/lib/describe_indexer.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/95072/faults/100604254)

## Acceptance criteria
- [ ] Fix the issue
- [ ] Mark this issue resolved in honeybadger

**Comment by jrgriffiniii** [comment]
I have confirmed that this is indeed blocking https://github.com/pulibrary/pdc_describe/issues/1491
