### ISSUE TITLE
Updated About Page for PDC Discovery

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_discovery#524]
Description:
Please see the attached document for the updated "About" page. The changes in the document should be applied to this page prior to the upcoming launch.

Acceptance Criteria:
- [ ] The changes provided in the attached document are applied to the "About" page for PDC Discovery. 

[PDC_Discovery_about_updated_101723.pdf](https://github.com/pulibrary/pdc_discovery/files/12928535/PDC_Discovery_about_updated_101723.pdf)

**Comment by matthewjchandler** [comment]
Thanks @hhkitsune for updating my title and Meghan's in there. I noticed that Wind's title needs to be updated, too

**Comment by kelynch** [comment]
Title adjusted to match https://library.princeton.edu/staff/hwcowles, per guidance from Hannah and Matt.  Thank you both!
