### ISSUE TITLE
Bug: Missing rights on landing pages for datasets

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_discovery#554]
It seems that the license/rights for data reuse is not available in v1.23.0.

It would be best to have this above the "Cite as" section and below the "Issue date:".

![Screenshot 2024-01-25 at 9 43 34 AM](https://github.com/pulibrary/pdc_discovery/assets/568286/e8cf3136-b6a3-411e-9433-ddf8b0df902b)

See for example: https://datacommons.princeton.edu/discovery/catalog/doi-10-34770-bm4s-t361

As this resource was created from within PDC Describe, we should display the license on the record for the user.

Acceptance Criteria:
- [ ] Ensure that the end-user can view the license information within a metadata field for the record
- [ ] Ensure that the URI for the license is used to generate a link for the metadata field
- [ ] Display the rights information using the same format that we use PDC Describe, e.g. "Creative Commons Attribution 4.0 International (CC BY)" where the short name "CC BY" is a link to the license.

**Comment by jrgriffiniii** [comment]
The license from DataSpace was excluded (purposely) from the migration, and hence, assigning points to this shall be postponed until there is further discussion.

**Comment by jrgriffiniii** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/554?planning-poker) with Zenhub @bess @carolyncole @hectorcorrea @kelynch @leefaisonr @JaymeeH

**Comment by jrgriffiniii** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/554?planning-poker) with Zenhub @jrgriffiniii
