### ISSUE TITLE
Plausible downloads are not showing up 

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_discovery#568]
Downloads on the show page are not being shown correctly.

The culprit seems to be the `period` value that is being used when we call the API: https://github.com/pulibrary/pdc_discovery/blob/main/app/models/plausible.rb#L31-L51

The breakdown API by default uses a `30d` period ([see documentation](https://plausible.io/docs/stats-api#get-apiv1statsbreakdown)) but we would like to display the value for all time.  

Unfortunately it does not seem that the API allows us to filer by the `all` value even though that's what they (Plausible) seem to use in the Dashboard: https://plausible.io/docs/stats-api#time-periods

Acceptance Criteria:

- [ ] Add `period=custom&date=2021-01-01,2021-01-31` to the Plausibe api call. `2021-01-31` should be current date
- [ ] Make sure plausible honors the request for longer time period (how do we know this, maybe choose an early deposit)

**Comment by hectorcorrea** [comment]
Deployed v1.25.3 that includes the period parameter using `12mo` and the values now look correct. But this will only work until we hit the 12 month mark. We should reach out to Plausible to see if there is a way to request `all` as the period.

**Comment by hectorcorrea** [comment]
The `period` parameter supports a [custom date range](https://plausible.io/docs/stats-api#time-periods) that might be what we need:

```
period=custom&date=2021-01-01,2021-01-31
```

**Comment by jrgriffiniii** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/568?planning-poker) with Zenhub @bess @carolyncole
