### ISSUE TITLE
Facet sorting by year and author not working

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_discovery#572]
Recently tried to sort the PPPL results of datasets in Discovery by year and authorship and the results were inconsistent with expectations.

See screenshots:

By year:
![Screen Shot 2024-02-27 at 7 26 25 AM](https://github.com/pulibrary/pdc_discovery/assets/20305734/1d4a1a38-ed85-447b-8c02-f27393f66d99)

By author:
![Screen Shot 2024-02-27 at 7 26 44 AM](https://github.com/pulibrary/pdc_discovery/assets/20305734/fe559bc0-3525-46ee-8161-b89c18ba9943)

Might be related to the home page show.  These items show both describe and dataspace.  PPPL content has been migrated, so we may not to worry about the dpsace content

Acceptance criteria:

- [ ] Utilize the new sorting field in the blacklight config may be something like "created_timestamp"

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/572?planning-poker) with Zenhub @bess @JaymeeH @jrgriffiniii @leefaisonr @hectorcorrea

**Comment by carolyncole** [comment]
@astrochun The way the current Author sort is working is that the authors of the paper are sorted in alphabetical order and then the one earliest in the alphabet is utilized.  So for a paper that has "Smith,Jane" as the first author and "Doe, John" as the second author, because Doe is earlier in the alphabet it is utilized for sorting.  I would assume that we should really just be sorting by the first author?

**Comment by astrochun** [comment]
> @astrochun The way the current Author sort is working is that the authors of the paper are sorted in alphabetical order and then the one earliest in the alphabet is utilized. So for a paper that has "Smith,Jane" as the first author and "Doe, John" as the second author, because Doe is earlier in the alphabet it is utilized for sorting. I would assume that we should really just be sorting by the first author?

Understood so then why is the example I provided shows Mollen before Gan? There should be some with last name starting in A's.
