### ISSUE TITLE
Link to "Getting Started with PDC" in PDC Discovery beta banner

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_discovery#596]
Add the [getting started](https://researchdata.princeton.edu/research-lifecycle-guide/getting-started-princeton-data-commons-describe-contributor) guide to the PDC Discovery beta banner.

PRDS will add the text for the link to this ticket when it is ready.

![Screenshot 2024-04-11 at 1 20 44 PM](https://github.com/pulibrary/pdc_discovery/assets/568286/785465b0-3770-4d8f-b5ca-b54b0469f5c7)

**Comment by neggink** [comment]
Replace text in PDC Discovery beta banner with:

Welcome to Princeton Data Commons Discovery! 
Have a look around our new website for the discovery and sharing of research data and[ let us know what you think](mailto:prds@princeton.edu). See our [Getting Started as a Princeton Data Commons Contributor](https://researchdata.princeton.edu/research-lifecycle-guide/getting-started-princeton-data-commons-describe-contributor) guide for instructions on how to publish your research data and code.
