### ISSUE TITLE
Missing items from Recently Published list

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#601]
As of v1.30.0, in staging, why isn't this Robotic Clay 3D Printing item on the most recently published list? 

![Screenshot 2024-04-10 at 9 58 53 AM](https://github.com/pulibrary/pdc_discovery/assets/65608/de45c597-1839-4ff8-b160-20e82e3737fe)
![Screenshot 2024-04-10 at 9 59 07 AM](https://github.com/pulibrary/pdc_discovery/assets/65608/382d18b8-e8a9-414b-9ff8-af5e88d313c9)

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/601?planning-poker) with Zenhub @carolyncole @JaymeeH @jrgriffiniii @leefaisonr
