### ISSUE TITLE
Crawlers and Globus

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_discovery#633]
We are having issues with Globus going down and all signs point to crawlers overloading our Globus endpoint. 

We have talked about rendering a page with all the metadata but not the links to the actual files when a crawler visit our site as a way to alleviate this issue.

See also #607 

Implementation Notes:

There is a gem that we can utilize: https://github.com/loadkpi/crawler_detect

Orangelight uses `voight_kampff` https://github.com/pulibrary/orangelight/commit/342b5f69385b0dc0bd05e1baeea130c18e6f6e8e

We should go with the Orangelight solution

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/633?planning-poker) with Zenhub @bess @JaymeeH @jrgriffiniii @leefaisonr @carolyncole
