### ISSUE TITLE
Deployment requires that `strscan` be updated to release 3.1.0 or later

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pdc_discovery#635]
This does not appear to be a problem originating with the code base, but seems to be related to the Ruby and `gem` environments for the `staging` and `production` server environments, as from `main`, one finds the following: https://github.com/pulibrary/pdc_discovery/blob/main/Gemfile#L35

This is found in the `Gemfile.lock` here: https://github.com/pulibrary/pdc_discovery/blob/main/Gemfile.lock#L503

I was required to resolve this only by manually issuing the following on the `staging` and `prod` host servers with:
```bash
gem update strscan
```

Ideally this is resolved exclusively from within https://github.com/pulibrary/princeton_ansible

**Comment by hectorcorrea** [comment]
@jrgriffiniii at the check-in meeting today we decided to rebuild the Discovery machines from scratch. @acozine will create a ticket for this and we'll go from there.
