### ISSUE TITLE
Update Rails Health Monitor to use new built in Solr monitor

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_discovery#662]
### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
- It will be better to utilize the [built in monitor ](https://github.com/lbeder/health-monitor-rails/pull/121)so we get upgrades and stay current with our colleagues.  Thanks @maxkadel  

### Acceptance criteria
 - [ ] Remove the custom Solr health Monitor
 - [ ] Configure the built in Solr health monitor
 - [ ] Solr is still monitored

### Implementation notes, if any

[Check out the docs](https://github.com/lbeder/health-monitor-rails?tab=readme-ov-file#solr)

**Comment by maxkadel** [comment]
See also - where we [added it to Orangelight](https://github.com/pulibrary/orangelight/pull/4062)

**Comment by carolyncole** [comment]
😢 Deleted the alias to test and neither our test nor the built in test actually failed
