### ISSUE TITLE
Upgrade to latest Blacklight release

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#67]
- [ ] Upgrade pdc_discovery to use Blacklight 8.0 when it is released, so we can build on the latest code and take advantage of accessibility improvements

**Comment by jrgriffiniii** [comment]
Blacklight 7.0 releases are currently used as dependencies, however, the 8.0 series of releases are not available yet. As this is not a heavily-customized version of Blacklight, might this be a good candidate for testing the Blacklight 8.0 release candidates?

**Comment by jrgriffiniii** [comment]
While volunteering to assist with testing for the Blacklight Community, it should not be a priority for this sprint.
