### ISSUE TITLE
Update link in PDC Discovery banner

### ISSUE THREAD

**Issue by meghantesterman** [pulibrary/pdc_discovery#673]
### Level of urgency
- [ ] High
- [ ] Moderate
- [X] Low

### Why is this maintenance needed?
- The PDC Discovery banner link 'Getting Started as a Princeton Data Commons Contributor' needs to be replaced to point to our new 'How to Submit' page (which is the PDC landing page)

### Acceptance criteria
 - [ ] Replace banner text and link as follows: See [How to Submit](https://datacommons.princeton.edu/describe/) for instructions on how to publish your research data and code.

### Implementation notes, if any
Screenshot of the link and text that need to be updated: 
<img width="1366" alt="Screenshot 2024-08-23 at 9 15 31 AM" src="https://github.com/user-attachments/assets/b20b08e7-03ee-44bf-9cdb-588cdd03906d">

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/673?planning-poker) with Zenhub @bess @carolyncole @JaymeeH @jrgriffiniii @leefaisonr
