### ISSUE TITLE
Import PDC Describe Version field into the index

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_discovery#694]
We are currently not importing from PDC Describe the version field (https://github.com/pulibrary/pdc_describe/issues/1935). 

We should so that we can expose it in the schema.org information (https://github.com/pulibrary/pdc_discovery/issues/353)

The version is exposed in the json from pdc describe as `version_number`.

Acceptance criteria:
- [ ] Version number is part of the index
- [ ] The version number is indexed as a non tokenized string
- [ ] The version number is exposed in the Schema.org tags

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_discovery/694?planning-poker) with Zenhub @bess @JaymeeH @jrgriffiniii @kelynch @leefaisonr
