### ISSUE TITLE
Each data set has a preferred citation

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#75]
As a student who is authoring a paper citing Princeton research data, I want to easily grab a citation that I can paste into my bibliography.

**ACCEPTANCE CRITERIA**
- [ ] Each data set has a citation that can be easily copied
- [ ] There is a "copy" button that copies the citation to the user's clipboard 

![Screen Shot 2021-11-03 at 1 52 12 PM](https://user-images.githubusercontent.com/65608/140165122-83f7e25e-3364-475e-9b7a-71e4674d1ce2.png)

This ticket is part of #74

**Comment by jrgriffiniii** [comment]
There are Ruby Gems used to handling citation generation, and these should be evaluated as options:

- https://github.com/sandbergja/blacklight-citeproc

**Comment by jrgriffiniii** [comment]
Another factor in implementation is determining the preferred citation style from stakeholders.
