### ISSUE TITLE
Set up google analytics

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#77]
**ACCEPTANCE CRITERIA**
- [ ] Google analytics is in place
- [ ] We (DRDS / PRDS) can go to the GA dashboard and see where traffic is coming from
- [ ] Investigate and report back:
  - [ ] Question: Does GA give us the ability to display the total number of times a page has been visited? 
  - [ ] Question: Can we use GA to count data downloads? 

![Screen Shot 2021-11-03 at 3.03.32 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/7ff94a63-9837-49ed-9b89-b2c174424192)

**Comment by jrgriffiniii** [comment]
We have determined that https://plausible.io/ provides an acceptable solution, and will pursue this later only if this proves to no longer be viable.
