### ISSUE TITLE
Princeton researchers can see their data being re-used

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#78]
As a Princeton researcher, I want evidence that my data is being re-used, so that I can keep abreast of new developments and demonstrate the influence of my work to funders and supervisors.

**Comment by astrochun** [comment]
Researchers at the Lab would like this as well. I think immediate metrics include downloads and views. True re-use is citations, but not many researchers follow best practices for citing work. For example, they might cite the original paper but not the data that they use.
