### ISSUE TITLE
Show users how often pages are being viewed

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#79]
As a scientist who has published my data, I want to see how often it has been viewed on PDC Discovery.

**ACCEPTANCE CRITERIA**
- [x] The show page for a data set displays a view count
- [x] This data is obtained from Plausible

![Screen Shot 2021-11-03 at 3 20 13 PM](https://user-images.githubusercontent.com/65608/140178495-06b4593d-6575-460b-9422-405450a351f6.png)

**Comment by jrgriffiniii** [comment]
Please see the API documentation for this: https://plausible.io/docs/stats-api

**Comment by hectorcorrea** [comment]
See https://github.com/pulibrary/pdc_discovery/issues/133 for display of downloads count
